"""bb

Revision ID: e59e580d7512
Revises: accb5dab5e59
Create Date: 2021-06-20 11:52:57.126615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e59e580d7512'
down_revision = 'accb5dab5e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('blog_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'blogs', ['blog_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'blog_id')
    # ### end Alembic commands ###
